/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "tertiary": "#001b21",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#051b3a",
        "inverse-surface": "#2f3034",
        "primary-fixed-dim": "#b2c5ff",
        "surface-bright": "#faf9fe",
        "on-error": "#ffffff",
        "primary-fixed": "#dae2ff",
        "tertiary-container": "#00313b",
        "secondary-fixed-dim": "#b4c7ee",
        "on-primary-fixed": "#001848",
        "on-primary-container": "#618eff",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#afecff",
        "inverse-on-surface": "#f1f0f5",
        "surface-container-high": "#e8e7ec",
        "on-surface": "#1a1c1f",
        "secondary-container": "#c2d5fd",
        "secondary-fixed": "#d6e3ff",
        "on-primary-fixed-variant": "#0040a2",
        "on-tertiary-fixed-variant": "#004e5d",
        "surface-container-highest": "#e3e2e7",
        "on-secondary-container": "#495c7e",
        "surface": "#faf9fe",
        "outline-variant": "#c4c6d0",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#48d7f9",
        "on-background": "#1a1c1f",
        "surface-variant": "#e3e2e7",
        "outline": "#747780",
        "surface-dim": "#dad9de",
        "surface-container-low": "#f4f3f8",
        "on-tertiary-fixed": "#001f27",
        "primary-container": "#00276a",
        "background": "#faf9fe",
        "primary": "#00143f",
        "secondary": "#4c5f81",
        "on-tertiary-container": "#00a1be",
        "on-secondary-fixed-variant": "#344768",
        "inverse-primary": "#b2c5ff",
        "surface-tint": "#0c56d0",
        "surface-container": "#eeedf2",
        "error-container": "#ffdad6",
        "on-surface-variant": "#43474f",
        "on-secondary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
